export const PARAM_KEYS = {
  TEMP_FROID_POSITIF_TRES_PERISSABLE: "TEMP_FROID_POSITIF_TRES_PERISSABLE",
  TEMP_FROID_POSITIF: "TEMP_FROID_POSITIF",
  TEMP_CONGELATION: "TEMP_CONGELATION",
  TEMP_RECEPTION_SURGELES: "TEMP_RECEPTION_SURGELES",
  TEMP_RECEPTION_SURGELES_TOLERANCE: "TEMP_RECEPTION_SURGELES_TOLERANCE",
  TEMP_CUISSON_COEUR: "TEMP_CUISSON_COEUR",
  TEMP_CUISSON_VOLAILLE: "TEMP_CUISSON_VOLAILLE",
  TEMP_REFROIDISSEMENT_CIBLE: "TEMP_REFROIDISSEMENT_CIBLE",
  TEMP_REFROIDISSEMENT_DUREE_MIN: "TEMP_REFROIDISSEMENT_DUREE_MIN",
  TEMP_LIAISON_CHAUDE: "TEMP_LIAISON_CHAUDE",
  TEMP_REMISE_DUREE_MIN: "TEMP_REMISE_DUREE_MIN",
  HUILE_COMPOSES_POLAIRES_MAX: "HUILE_COMPOSES_POLAIRES_MAX",
  PLAT_TEMOIN_JOURS: "PLAT_TEMOIN_JOURS",
  PLAT_TEMOIN_TEMP_MAX: "PLAT_TEMOIN_TEMP_MAX",
  RELEVE_MATIN_LIMITE: "RELEVE_MATIN_LIMITE",
  RELEVE_SOIR_LIMITE: "RELEVE_SOIR_LIMITE",
  DLC_SECONDAIRE_DECONGEL_HEURES: "DLC_SECONDAIRE_DECONGEL_HEURES",
  DLC_SECONDAIRE_OUVERTURE_HEURES: "DLC_SECONDAIRE_OUVERTURE_HEURES",
  FORMATION_ALERTE_JOURS: "FORMATION_ALERTE_JOURS",
  ALIMCONFIANCE_DATE: "ALIMCONFIANCE_DATE",
  ALIMCONFIANCE_RESULTAT: "ALIMCONFIANCE_RESULTAT",
  NUISIBLES_PRESTATAIRE: "NUISIBLES_PRESTATAIRE",
  EMAIL_ALERTES: "EMAIL_ALERTES",
} as const;

export type ParamKey = (typeof PARAM_KEYS)[keyof typeof PARAM_KEYS];

export type ParamMap = Record<string, string>;

/** Valeurs de seed uniquement — jamais lues par la logique métier. */
export const SEED_PARAMETRES: Record<ParamKey, string> = {
  TEMP_FROID_POSITIF_TRES_PERISSABLE: "3",
  TEMP_FROID_POSITIF: "4",
  TEMP_CONGELATION: "-18",
  TEMP_RECEPTION_SURGELES: "-18",
  TEMP_RECEPTION_SURGELES_TOLERANCE: "-15",
  TEMP_CUISSON_COEUR: "63",
  TEMP_CUISSON_VOLAILLE: "74",
  TEMP_REFROIDISSEMENT_CIBLE: "10",
  TEMP_REFROIDISSEMENT_DUREE_MIN: "120",
  TEMP_LIAISON_CHAUDE: "63",
  TEMP_REMISE_DUREE_MIN: "60",
  HUILE_COMPOSES_POLAIRES_MAX: "25",
  PLAT_TEMOIN_JOURS: "5",
  PLAT_TEMOIN_TEMP_MAX: "3",
  RELEVE_MATIN_LIMITE: "11:00",
  RELEVE_SOIR_LIMITE: "18:00",
  DLC_SECONDAIRE_DECONGEL_HEURES: "24",
  DLC_SECONDAIRE_OUVERTURE_HEURES: "48",
  FORMATION_ALERTE_JOURS: "90",
  ALIMCONFIANCE_DATE: "",
  ALIMCONFIANCE_RESULTAT: "",
  NUISIBLES_PRESTATAIRE: "À renseigner",
  EMAIL_ALERTES: "gerant@luxas.local",
};

export function requireParam(params: ParamMap, cle: ParamKey): string {
  const valeur = params[cle];
  if (valeur === undefined || valeur === "") {
    throw new Error(`Paramètre manquant: ${cle}`);
  }
  return valeur;
}

export function requireParamNumber(params: ParamMap, cle: ParamKey): number {
  const n = Number.parseFloat(requireParam(params, cle));
  if (!Number.isFinite(n)) {
    throw new Error(`Paramètre numérique invalide: ${cle}`);
  }
  return n;
}
